name: dbt_ci_cd
on:
  push:
    branches:
      - main
  pull_request:
    branches: [ main ]

 env:
   DBT_PROJECT_DIR: C:/Users/USER/Documents/Dbt_projects/MESAGAN_PROJECTS
   DBT_PROFILES_DIR: C:/Users/USER/.dbt
   DBT_GCP_JSON_KEY_FILE_LOCATION: /tmp/dbt-tutorial-mesagan-a39f8d7a3b3b.json
   DBT_GCP_JSON_KEY_FILE: ${{ secrets.dbt-tutorial-mesagan-a39f8d7a3b3b.json }}

 jobs:
   dbt_ci_cd:
     runs-on: ubuntu-latest
     
     steps:
     - name: Checkout code
       uses: actions/checkout@v2

     - name: Set up Python
       uses: actions/setup-python@v2
       with:
         python-version: '3.9.x'

     - name: Install dbt
       run: |
         python -m pip install --upgrade pip
         pip install dbt-core==1.7.18 dbt-bigquery==1.7.9

     - name: Set up Google Cloud authentication
       env:
         DBT_KEYFILE: ${{ secrets.dbt-tutorial-mesagan-a39f8d7a3b3b.json }}
       run: |
         echo "$DBT_KEYFILE" > /tmp/sdbt-tutorial-mesagan-a39f8d7a3b3b.json
         export GOOGLE_APPLICATION_CREDENTIALS=/tmp/dbt-tutorial-mesagan-a39f8d7a3b3b.json

     - name: Run dbt models
       run: |
         dbt deps
         dbt seed
         dbt run

     - name: Test dbt models
       run: |
         dbt test


        
